CREATE TABLE ALUMNO
(
		IDALUMNO 		NUMBER(8)		CONSTRAINT IDALUMNO PRIMARY KEY(IDALUMNO),
		CURP 			VARCHAR2(18) 	CONSTRAINT CURP_NN   NOT NULL,
		NOMBREALU		VARCHAR2(55) 	CONSTRAINT ALUMPM_NN NOT NULL,
		APELLIDOP		VARCHAR2(45) 	CONSTRAINT ALUMPA_NN NOT NULL,
		APELLIDOM		VARCHAR2(45) 	CONSTRAINT ALUMSA_NN NOT NULL,
		SEXO			CHAR 			CONSTRAINT SEXO_A CHECK(SEXO IN ('M','H')) CONSTRAINT SEXO_ANN NOT NULL,
		FECHANAC		DATE		 	CONSTRAINT FECHANAC_NN NOT NULL,
		ESTADO		    VARCHAR2(45)    CONSTRAINT ESTADO_NN NOT NULL,
		MUNICIPIO 		VARCHAR2(45) 	CONSTRAINT MUNICIPIO_NN NOT NULL
);

CREATE TABLE RESPONSABLE
(
		IDRESPONSABLE 	CHAR(8) 		CONSTRAINT IDRESPONSABLE_PK PRIMARY KEY(IDRESPONSABLE),
		NOMBRERESP	 	VARCHAR2(55) 	CONSTRAINT NOMBRERESP_NN NOT NULL,
		APELLIDOP 		VARCHAR2(45)	CONSTRAINT RESPONPA_NN NOT NULL,
		APELLIDOM 		VARCHAR2(45) 	CONSTRAINT RESPONSA_NN NOT NULL,
		SEXO 			CHAR 			CONSTRAINT SEXO_R CHECK(SEXO IN ('M','H')) CONSTRAINT SEXO_RNN NOT NULL,
		EDAD 			NUMBER(2) 		CONSTRAINT EDAD_RRANGO CHECK(EDAD<50 AND EDAD>15) CONSTRAINT EDAD_RNN NOT NULL,
		PARENTESCO 		VARCHAR2(45)	CONSTRAINT PARENTESCO_NN NOT NULL,
		CALLE 			VARCHAR2(45) 	CONSTRAINT CALLE_NN NOT NULL,
		COLONIA 		VARCHAR2(45) 	CONSTRAINT COLONIA_NN NOT NULL,
		NUMERO 			NUMBER(6) 		CONSTRAINT NUMERO_NN NOT NULL,
		MOVIL 			NUMBER(15) 		
);
--EL ATRIBUTO MULTIVALUADO SE CREA COMO UNA ENTIDAD DEBIL
CREATE TABLE TELEFONO
(
		IDRESPONSABLE 	NUMBER(8) 		CONSTRAINT TIDRESPONSABLE_FK FOREIGN KEY(IDRESPONSABLE) REFERENCES RESPONSABLE,
		TELEFONO 		NUMBER(10) 		CONSTRAINT TELEFONO_NN NOT NULL
);
--EL ATRIBUTO MULTIVALUADO SE CREA COMO UNA ENTIDAD DEBIL
CREATE TABLE HORARIO
(
		IDRESPONSABLE 	NUMBER(8) 		CONSTRAINT HIDRESPONSABLE_FK FOREIGN KEY(IDRESPONSABLE) REFERENCES RESPONSABLE,
		HORARIO 		VARCHAR2(45) 	CONSTRAINT HORARIO_NN NOT NULL
);


CREATE TABLE ALUMNO_RESPONSABLE
(
	IDALUMNO			NUMBER(8) 		CONSTRAINT IDALUMNO_FK FOREIGN KEY(IDALUMNO) REFERENCES ALUMNO,
	IDRESPONSABLE 		CHAR(8)			CONSTRAINT A_RIDRESPONSABLE_FK FOREIGN KEY(IDRESPONSABLE) REFERENCES IDRESPONSABLE
);

CREATE TABLE TUTOR
(
		RFC 			CHAR(13) 		CONSTRAINT RFC_PK PRIMARY KEY(RFC),
		IDRESPONSABLE 	NUMBER(8) 		CONSTRAINT TIDRESPONSABLE_FK FOREIGN KEY(IDRESPONSABLE) REFERENCES RESPONSABLE
);
--SE PASA LA PK DE TUTOR A ALUMNO
ALTER TABLE ALUMNO ADD 	RFC CHAR(13) 	CONSTRAINT ARFC_FK  FOREIGN KEY(RFC) REFERENCES TUTOR;

CREATE TABLE  INSCRIPCION
(
		IDINSCRIPCION 	NUMBER(8) 		CONSTRAINT IDINSCRIPCION_PK PRIMARY KEY(IDINSCRIPCION),
		CICLOESCOLAR 	VARCHAR2(20) 	CONSTRAINT CICLOESCOLAR_NN NOT NULL,
		FECHAINSCRIPCION DATE 			CONSTRAINT FECHAINSCRIPCION_NN NOT NULL,
		NUMEROMENSUALIDADES NUMBER(2)   CONSTRAINT NUMEROMENSUALIDADES_RANGE CHECK(NUMEROMENSUALIDADES IN(1,2,3,6,10,12)) CONSTRAINT NUMEROMENSUALIDADES_NN NOT NULL
);

ALTER TABLE INSCRIPCION ADD IDALUMNO NUMBER(8) CONSTRAINT IDALUMNO_FK FOREIGN KEY(IDALUMNO) REFERENCES ALUMNO; 

--TERCERA PARTE 
CREATE TABLE NIVEL
(
		IDNIVEL 		NUMBER(8) 		CONSTRAINT IDNIVEL_PK PRIMARY KEY(IDNIVEL),
		NIVEL			VARCHAR2(20) 		CONSTRAINT NIVEL_NN NOT NULL
);


CREATE TABLE NIVEL_GRADO
(
		IDNIVEL 		NUMBER(8) 		CONSTRAINT IDNIVEL_FK FOREIGN KEY(IDNIVEL) REFERENCES NIVEL,
		IDGRADO			NUMBER(8),
		CONSTRAINT NIVEL_GRADO_PK PRIMARY KEY(IDNIVEL,IDGRUPO)
);

CREATE TABLE GRUPO
(
		IDGRUPO 		NUMBER(8) 		CONSTRAINT IDGRUPO_PK 	PRIMARY KEY(IDGRUPO),
		GRUPO 			VARCHAR2(3) 	CONSTRAINT GRUPO_NN 	NOT NULL,
		CONSTRAINT NIVGRAD_GPO FOREIGN KEY(IDNIVEL,IDGRUPO) REFERENCES NIVEL_GRADO
);

CREATE TABLE GRADO_SERVICIO
(
		PRECIO 			NUMBER(12,2) 	CONSTRAINT PRECIO_NN NOT NULL,
		IDNIVEL 		NUMBER(8),
		IDGRADO 		NUMBER(8),
		CONSTRAINT GRAD_SRVCE_FK FOREIGN KEY(IDNIVEL,IDGRUPO) REFERENCES NIVEL_GRADO
);

--TALAS NUEVAS
CREATE TABLE CARGO
(
	IDCARGO		NUMBER(8) CONSTRAINT IDCARGO_PK PRIMARY KEY(IDCARGO),
	FECHACARGO 	DATE  	CONSTRAINT FECHACARGO_NN NOT NULL,
	FECHAVEN 	DATE  	CONSTRAINT FECHAVEN_NN NOT NULL,
	FECHAPAGO 	DATE 	CONSTRAINT FECHAPAGO_NN NOT NULL,
	IMPORTE 	NUMBER(12,2) CONSTRAINT IMPORTE_NN NOT NULL,
	ABONO 		NUMBER(12,2) CONSTRAINT ABONO_C DEFAULT 0,
	CVS 		CHAR(2)
);

CREATE TABLE DESCUENTO
(
	IDDESCUENTO 	NUMBER(8)		 	CONSTRAINT IDDESCUENTO_PK PRIMARY KEY(IDDESCUENTO),
	FECHADESC 		DATE 			CONSTRAINT FECHADESC_NN NOT NULL,
	IMPORTE 		NUMBER(12,2) 	CONSTRAINT IMPORTE_D_NN NOT NULL,
	APLICADO 		CHAR(2) 		CONSTRAINT APLICADO_D DEFAULT 'NO',
	CARGO 			CHAR(8) 		CONSTRAINT CARGO_NN NOT NULL
);
