CREATE TABLE ALUMNO
(
		IDALUMNO 		NUMBER(8),
		CURP 			VARCHAR2(18) 	CONSTRAINT CURP_NN   NOT NULL,
		NOMBREALU		VARCHAR2(55) 	CONSTRAINT ALUMPM_NN NOT NULL,
		APELLIDOP		VARCHAR2(45) 	CONSTRAINT ALUMPA_NN NOT NULL,
		APELLIDOM		VARCHAR2(45) 	CONSTRAINT ALUMSA_NN NOT NULL,
		SEXO			CHAR 			CONSTRAINT SEXO_ANN	 NOT NULL,
		FECHANAC		DATE		 	CONSTRAINT FECHANAC_NN  NOT NULL,
		ESTADO		    VARCHAR2(45)    CONSTRAINT ESTADO_NN 	NOT NULL,
		MUNICIPIO 		VARCHAR2(45) 	CONSTRAINT MUNICIPIO_NN NOT NULL,
		RFC 			CHAR(13),
		CONSTRAINT IDALUMNO_PK PRIMARY KEY (IDALUMNO),
		CONSTRAINT SEXO_A CHECK(SEXO IN ('M','H'))
);

CREATE TABLE RESPONSABLE
(
		IDRESPONSABLE 	NUMBER(8),
		NOMBRERESP	 	VARCHAR2(55) 	CONSTRAINT NOMBRERESP_NN NOT NULL,
		APELLIDOP 		VARCHAR2(45)	CONSTRAINT RESPONPA_NN 	 NOT NULL,
		APELLIDOM 		VARCHAR2(45) 	CONSTRAINT RESPONSA_NN 	 NOT NULL,
		SEXO 			CHAR 			CONSTRAINT SEXO_RNN 	 NOT NULL,
		EDAD 			NUMBER(2) 		CONSTRAINT EDAD_RNN 	 NOT NULL,
		PARENTESCO 		VARCHAR2(45)	CONSTRAINT PARENTESCO_NN NOT NULL,
		CALLE 			VARCHAR2(45) 	CONSTRAINT CALLE_NN 	 NOT NULL,
		COLONIA 		VARCHAR2(45) 	CONSTRAINT COLONIA_NN 	 NOT NULL,
		NUMERO 			NUMBER(6) 		CONSTRAINT NUMERO_NN 	 NOT NULL,
		MOVIL 			NUMBER(15),
		CONSTRAINT IDRESPONSABLE_PK PRIMARY KEY(IDRESPONSABLE),
		CONSTRAINT SEXO_R CHECK(SEXO IN ('M','H')),
		CONSTRAINT EDAD_RRANGO CHECK(EDAD<50 AND EDAD>15)		
);
--EL ATRIBUTO MULTIVALUADO SE CREA COMO UNA ENTIDAD DEBIL
CREATE TABLE TELEFONOHORARIO
(
		IDRESPONSABLE 	NUMBER(8),
		TELEFONO 		NUMBER(10) 		CONSTRAINT TELEFONO_NN NOT NULL,
		HORARIO 		VARCHAR2(45) 	CONSTRAINT HORARIO_NN  NOT NULL,
		CONSTRAINT TIDRESPONSABLE_FK FOREIGN KEY(IDRESPONSABLE) REFERENCES RESPONSABLE
);


CREATE TABLE ALUMNO_RESPONSABLE
(
	IDALUMNO			NUMBER(8),
	IDRESPONSABLE 		NUMBER(8),
	CONSTRAINT IDALUMNO_FK FOREIGN KEY(IDALUMNO) REFERENCES ALUMNO,
	CONSTRAINT A_RIDRESPONSABLE_FK FOREIGN KEY(IDRESPONSABLE) REFERENCES RESPONSABLE
);

CREATE TABLE TUTOR
(
		RFC 			CHAR(13),
		IDRESPONSABLE 	NUMBER(8) CONSTRAINT T_IDRESPONSABLE_NN NOT NULL,
		CONSTRAINT RFC_PK PRIMARY KEY(RFC),
		CONSTRAINT TUTORIDRESPONSABLE_FK FOREIGN KEY(IDRESPONSABLE) REFERENCES RESPONSABLE
);
--SE PASA LA PK DE TUTOR A ALUMNO
--ALTER TABLE ALUMNO ADD 	RFC CHAR(13);
ALTER TABLE ALUMNO ADD CONSTRAINT ARFC_FK  FOREIGN KEY(RFC) REFERENCES TUTOR;
--MARCA :)
CREATE TABLE  INSCRIPCION
(
		IDINSCRIPCION 		NUMBER(8),
		CICLOESCOLAR 		VARCHAR2(20) 	CONSTRAINT CICLOESCOLAR_NN NOT NULL,
		FECHAINSCRIPCION 	DATE 			CONSTRAINT FECHAINSCRIPCION_NN NOT NULL,
		NUMEROMENSUALIDADES NUMBER(2)   	CONSTRAINT NUMEROMENSUALIDADES_NN NOT NULL,
		IDALUMNO 			NUMBER(8)		CONSTRAINT I_IDALUMNO_NN NOT NULL,
		IDNIVEL 		NUMBER(8)			CONSTRAINT I_IDNIVEL_NN 	NOT NULL,
		IDGRADO			NUMBER(8)			CONSTRAINT I_IDGRADO_NN 	NOT NULL,
		CONSTRAINT IDINSCRIPCION_PK PRIMARY KEY(IDINSCRIPCION)
);

--ALTER TABLE INSCRIPCION ADD IDALUMNO NUMBER(8);
ALTER TABLE INSCRIPCION ADD CONSTRAINT IIDALUMNO_FK FOREIGN KEY(IDALUMNO) REFERENCES ALUMNO; 

--TERCERA PARTE 
--ME EQUIVOQUÉ E INCLUÍ EL CHECK EN UNA TABLA AJENA, ES AQUÍ DONDE VA EL CHECK
CREATE TABLE NIVEL
(
		IDNIVEL 		NUMBER(8),
		NIVEL			VARCHAR2(20) 		CONSTRAINT NIVEL_NN NOT NULL,
		CONSTRAINT IDNIVEL_PK PRIMARY KEY(IDNIVEL),
		CONSTRAINT NIVELES_UNICOS UNIQUE(NIVEL)
);

--NO NOS COVIENE RESTRINGIR CON CHECKS,ESO PRODUCE UAN BASE ESTATICA


CREATE TABLE NIVEL_GRADO
(
		IDNIVEL 		NUMBER(8),
		IDGRADO			NUMBER(8)		CONSTRAINT IDGRADO_NN 	NOT NULL,
		CONSTRAINT IDNIVEL_FK FOREIGN KEY(IDNIVEL) REFERENCES NIVEL,
		CONSTRAINT NIVEL_GRADO_PK PRIMARY KEY(IDNIVEL,IDGRADO)
);

--SE AÑADE LA RELACION ENTRE NIVEL_GRADO E INSCRIPCION
--ALTER TABLE INSCRIPCION ADD IDNIVEL NUMBER(8);
--ALTER TABLE INSCRIPCION ADD IDGRADO NUMBER(8);
ALTER TABLE INSCRIPCION ADD CONSTRAINT I_IDNIVEL_GRADO_FK FOREIGN KEY(IDNIVEL,IDGRADO) REFERENCES NIVEL_GRADO; 

CREATE TABLE GRUPO
(
		IDGRUPO 		NUMBER(8),
		GRUPO 			VARCHAR2(3) 	CONSTRAINT GRUPO_NN 	NOT NULL,
		IDNIVEL 		NUMBER(8)		CONSTRAINT GIDNIVEL_NN 	NOT NULL,
		IDGRADO			NUMBER(8)		CONSTRAINT GIDGRADO_NN 	NOT NULL,
		CONSTRAINT NIVGRAD_GPO FOREIGN KEY(IDNIVEL,IDGRADO) REFERENCES NIVEL_GRADO,
		CONSTRAINT IDGRUPO_PK 	PRIMARY KEY(IDGRUPO)
);

--EL CONSTRAINT SRVC_TIPO_U ES PARA QUE NO REPITA SERVICIOS AL INSERTAR
CREATE TABLE SERVICIO
(
		IDSERVICIO 		NUMBER(8),
		TIPO 			VARCHAR2(45	)	CONSTRAINT TIPO_NN 			NOT NULL,
		PERIODOPAGO		NUMBER(2)		CONSTRAINT PERIODOPAGO_NN 	NOT NULL,
		CONSTRAINT SRVC_TIPO_U UNIQUE(TIPO),
		CONSTRAINT IDSERVICIO_PK 	PRIMARY KEY(IDSERVICIO)
);

/*
QUITE EL CHECK PORQUE NO PODEMOS LIMITAR EL TIPO MEDIANTE UN CHECK,MEJOR QUE SEA MEDIANTE UN PROCEDIMIENTO
YA QUE SI LO DEJAMOS COMO CHECK NOS COSTARA TRABAJO EL LIMITAR O AGREGAR SERVICIOS,MEJOR UN PROCEDIMIENTO QUE SE LLAME INSCRIPCIONES
Y YA DENTRO DE ESE METEMOS LOS 'PRIMARIA','SECUNDARIA','ETC'
--CONSTRAINT SERVICIOS CHECK(TIPO IN('JARDIN DE NIÑOS','PRIMARIA','SECUNDARIA','PREPARATORIA'))
*/
CREATE TABLE GRADO_SERVICIO
(
		PRECIO 			NUMBER(12,2) 	CONSTRAINT PRECIO_NN 		NOT NULL,
		IDNIVEL 		NUMBER(8)		CONSTRAINT GSIDNIVEL_NN 	NOT NULL,
		IDGRADO 		NUMBER(8)		CONSTRAINT GSIDGRADO_NN 	NOT NULL,
		IDSERVICIO 		NUMBER(8)		CONSTRAINT GSIDSERVICIO_NN 	NOT NULL,
		CONSTRAINT GRAD_SRVCE_FK FOREIGN KEY(IDNIVEL,IDGRADO) REFERENCES NIVEL_GRADO,
		CONSTRAINT GS_SRVCE_FK FOREIGN KEY(IDSERVICIO) REFERENCES SERVICIO
);

--TALAS NUEVAS
--CARGO ES CAMPO RECURSIVO Y PUEDE SER NULL
--LA LLAVE FORANEA C_SRVCE_FK ES PARA QUE SÓLO CONTENGA SERVICIOS EXISTENTES
CREATE TABLE CARGO
(
	IDCARGO		NUMBER(8),
	FECHACARGO 	DATE  	CONSTRAINT FECHACARGO_NN 	NOT NULL,
	FECHAVEN 	DATE  	CONSTRAINT FECHAVEN_NN 		NOT NULL,
	FECHAPAGO 	DATE 	CONSTRAINT FECHAPAGO_NN 	NOT NULL,
	IMPORTE 	NUMBER(12,2) CONSTRAINT IMPORTE_NN 	NOT NULL,
	ABONO 		NUMBER(12,2) DEFAULT 0,
	CVS 		CHAR(2),
	CARGO 		NUMBER(8),
	IDINSCRIPCION NUMBER(8) CONSTRAINT C_IDINSCRIPCION_NN 	NOT NULL,
	IDSERVICIO    NUMBER(8) CONSTRAINT C_IDSERVICIO_NN 	NOT NULL,
	CONSTRAINT IDCARGO_PK PRIMARY KEY(IDCARGO),
	CONSTRAINT C_INSCRIP_FK FOREIGN KEY(IDINSCRIPCION) REFERENCES INSCRIPCION,
	CONSTRAINT C_SRVCE_FK FOREIGN KEY(IDSERVICIO) REFERENCES SERVICIO
);

CREATE TABLE DESCUENTO
(
	IDDESCUENTO 	NUMBER(8),
	FECHADESC 		DATE 			CONSTRAINT FECHADESC_NN NOT NULL,
	IMPORTE 		NUMBER(12,2) 	CONSTRAINT IMPORTE_D_NN NOT NULL,
	APLICADO 		CHAR(2) 		DEFAULT 'NO',
	IDCARGO 		NUMBER(8) 		CONSTRAINT CARGO_NN NOT NULL,
	CARGOAPLICADO   NUMBER(8),
	CONSTRAINT IDDESCUENTO_PK PRIMARY KEY(IDDESCUENTO),
	CONSTRAINT CARGOAPLICADO_FK FOREIGN KEY(CARGOAPLICADO) REFERENCES CARGO(IDCARGO),
	CONSTRAINT IDCARGO_FK FOREIGN KEY(IDCARGO) REFERENCES CARGO(IDCARGO)
);

COMMIT;
--MOVI LOS PROCEDIMIENTOS A OTRO ARCHIVO PROCEDIMIENTOS_SERVICIOS.SQL